### ISSUE TITLE
Change the color and format of the legend on the map to be different for each dataset

### ISSUE THREAD

**Issue by seamuslo** [mitmedialab/Vida_Modeling#24]
I think it would be good to modify the script so that the color and format of the legend is different where necessary.

**Comment by seamuslo** [comment]
For instance, in the example below, because the change in workplace mobility measures are negative, the lightest values actually end up being the biggest change, which is not the normal convention for a choropleth map.
![image](https://user-images.githubusercontent.com/46720568/97012927-69988880-1516-11eb-9f2f-305a2ae60099.png)


Additionally, while the bounds for some of the maps seem to be chosen well in the currently implemented functionality, for this Farmer Terms of Trade Example (the values for which are also shown below), the legend has a range of 0 to 100, when all the values are in the 90-105 range, making the map less useful:
![image](https://user-images.githubusercontent.com/46720568/97012888-5d143000-1516-11eb-8e05-d9e8a5c414cd.png)


![image](https://user-images.githubusercontent.com/46720568/97012858-51c10480-1516-11eb-96a0-953e4cc2c1be.png)

Do you have any first pass thoughts on how to implement these? They are obviously not 100% essential, but I do think they would make the prototype significantly better in terms of interpreting the data.

**Comment by jackreid** [comment]
I realized that this should be merged with another issue, so the merged issue is now available at #34
