### ISSUE TITLE
Reorganizing temporal data drop down lists as some of them get quite long

### ISSUE THREAD

**Issue by jackreid** [mitmedialab/Vida_Modeling#41]
The obvious example of this is the Indonesian Economy category. There are two immediate solutions that present themselves.

1. The easier solution, just make a category(ies) so that each category contains fewer entries, maybe things like GDP, Expenditures, Misc. This would be as simple as going through the Indonesian SD objects in SDlib and changing the category value for the Economy objects to something else. The code will automatically pickup on the new categories and add them to the dropdown list.

2. Slightly harder solution. Have the code detect when there are more than a certain number of entries in a category and split the category, at the top level menu or a new dropdown within the Economy section.

**Comment by seamuslo** [comment]
I went with option 1 for now - just categorized them into "nationwide" and "regional" economic trends which cleaned things up well. If there's a lull sometime, I'll look into option 2
